package com.example.weatherappjc.core

import com.example.weatherappjc.R

val weatherAnimation = mapOf(
    "Cloudy" to R.raw.cloudy,
    "Sunny " to R.raw.anim_sunny,
    "Overcast " to R.raw.cloudy,
    "Clear" to R.raw.anim_sunny,
    "Partly cloudy" to R.raw.cloudy,
    "Mist" to R.raw.mist_foggy,
    "Fog" to R.raw.mist_foggy,
    "Patchy rain possible" to R.raw.possible_rain,
    "Patchy rain nearby" to R.raw.possible_rain,
    "Patchy snow possible" to R.raw.possible_snow,
    "Patchy sleet possible" to R.raw.snow,
    "Patchy freezing drizzle possible" to R.raw.freeze,
    "Thundery outbreaks possible" to R.raw.thunder,
    "Blowing snow" to R.raw.speed_snow,
    "Blizzard" to R.raw.windy,
    "Freezing fog" to R.raw.mist_foggy,
    "Patchy light drizzle" to R.raw.possible_rain,
    "Light drizzle" to R.raw.possible_rain,
    "Freezing drizzle" to R.raw.snow_with_rain,
    "Heavy freezing drizzle" to R.raw.snow_with_rain,
    "Patchy light rain" to R.raw.possible_rain,
    "Light rain" to R.raw.possible_rain,
    "Moderate rain at times" to R.raw.possible_rain,
    "Moderate rain" to R.raw.possible_rain,
    "Heavy rain at times" to R.raw.heavy_rain,
    "Heavy rain" to R.raw.heavy_rain,
    "Light freezing rain" to R.raw.snow_with_rain,
    "Moderate or heavy freezing" to R.raw.possible_snow,
    "Light sleet" to R.raw.possible_snow,
    "Moderate or heavy sleet" to R.raw.possible_snow,
    "Patchy light snow" to R.raw.possible_snow,
    "Light snow" to R.raw.possible_snow,
    "Patchy moderate snow" to R.raw.possible_snow,
    "Moderate snow" to R.raw.possible_snow,
    "Patchy heavy snow" to R.raw.speed_snow,
    "Heavy snow" to R.raw.speed_snow,
    "Ice pellets" to R.raw.freeze,
    "Light rain shower" to R.raw.possible_rain,
    "Moderate or heavy rain shower" to R.raw.heavy_rain,
    "Torrential rain shower" to R.raw.heavy_rain,
    "Light sleet showers" to R.raw.possible_snow,
    "Moderate or heavy sleet showers" to R.raw.snow_with_rain,
    "Light snow showers" to R.raw.possible_snow,
    "Moderate or heavy snow showers" to R.raw.speed_snow,
    "Light showers of ice pellets" to R.raw.possible_snow,
    "Moderate or heavy showers of ice pellets" to R.raw.snow_with_rain,
    "Patchy light rain with thunder" to R.raw.rain_with_thunder,
    "Moderate or heavy rain with thunder" to R.raw.rain_with_thunder,
    "Patchy light snow with thunder" to R.raw.heavy_snow_thunder,
    "Moderate or heavy snow with thunder" to R.raw.heavy_snow_thunder
)
